server:
  port: 8001

rocketmq:
  producer:
    # 是否启动生产者
    isOnOff: on
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    maxMessageSize: 4096
    sendMsgTimeOut: 3000
    retryTimesWhenSendFailed: 2
  consumer:
    ifOnOff: on
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    # 该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: topic-*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    # 设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1
    reConsumeTimes: 3
spring:
  application:
    name: springboot-demo